<?php if($this->isAdmin) { ?>
   <a href="/customer/add"><button>Add customer</button></a>
<?php } ?>

<div class="g12">
   <h1>Customers</h1>
   <table class="datatable">
      <thead>
         <tr>
            <th>Name</th>
            <th>Type</th>
            <th>Adress</th>
            <th>Phone</th>
            <th>Mail</th>
         </tr>
      </thead>
      <tbody>

         <?php
            foreach($this->customers as $customer) {

            $color = '';
            if($customer['type'] == 'private') {
               $color = 'yellow';
            } elseif ($customer['type'] == 'company') {
               $color = 'blue';
            }
         ?>

            <tr class="clickable <?= $color; ?>" data-link="/customer/view/<?= $customer['customer_id'] ?>">
               <td><?= $customer['name'] ?></td>
               <td><?= $customer['type'] ?>
               <td>
                  <a target="_blank" href="http://maps.google.com/?q=<?= $customer['customer_adress'] ?>, <?= $customer['zip_code'] ?> <?= $customer['city'] ?>, <?= $customer['country'] ?>">
                     <?= $customer['customer_adress'] ?>
                  </a>
               </td>
               <td><a href="tel:<?= $customer['phone'] ?>"><?= $customer['phone'] ?></td>
               <td><a href="mailto:<?= $customer['mail'] ?>"><?= $customer['mail'] ?></a></td>
            </tr>

         <?php } ?>

      </tbody>
   </table>
</div>