<div class="g12 nodrop">
	<h1>Dashboard</h1>
</div>

<div class="g6 widgets">

	<div class="widget" id="widget_order_date" data-icon="calendar">
		<h3 class="handle">Utkörningsdatum</h3>
		<div>
			<table class="datatable">
				<thead>
					<tr>
						<th>Datum</th>
						<th>Order</th>
					</tr>
				</thead>
				<tbody>

					<?php foreach($this->deliveryDates as $date) { ?>

					<tr>
						<td><?= ($date['delivery_date'] ? date('Y-m-d', $date['delivery_date']): ''); ?></td>
						<td><?= $date['orders']; ?></td>
					</tr>

					<?php } ?>

				</tbody>
			</table>
		</div>
	</div>

	<div class="widget" id="widget_ordered_products" data-icon="abacus">
		<h3 class="handle">Beställda produkter</h3>
		<div>
			<table class="datatable">
				<thead>
					<tr>
						<th>Produkt</th>
						<th>Antal</th>
					</tr>
				</thead>
				<tbody>

					<?php foreach($this->orderedProducts as $product) { ?>

						<tr>
							<td><a href="/product/view/<?= $product['product_id'] ?>"><?= $product['product'] ?></a></td>
							<td><?= $product['quantity'] ?></td>
						</tr>

					<?php } ?>

				</tbody>
			</table>
		</div>
	</div>

	<div class="widget" id="widget_mails" data-icon="mail">
		<h3 class="handle">Epostadresser</h3>
		<div>
			<h5>
				Vi har <i><?= $this->numMails ?></i> adresser i systemet.
			</h5>
			<textarea><?= $this->mails ?></textarea>
		</div>
	</div>

</div>


<div class="g6 widgets">
		
	<div class="widget" id="widget_unconfirmedorders" data-icon="create_write">
		<h3 class="handle">Obehandlade ordrar</h3>
		<div>
			<span><?= $this->unconfirmedOrders['num_orders'] ?></span>
		</div>
	</div>


	<div class="widget number-widget" id="widget_CRM" data-icon="folder_love">
		<h3 class="handle">Ärendehantering</h3>
		<div>
			<ul>
				<li><a href=""><span><?= $this->crm['active'] ?></span> Aktiva</a></li>
				<li><a href=""><span><?= $this->crm['today'] ?></span> Satta till idag</a></li>
			</ul>
		</div>
	</div>


	<div class="widget" id="overdue-invoice" data-icon="cash_register">
		<h3 class="handle">Förfallna fakturor</h3>
		<div>
			<table class="datatable">
				<thead>
					<tr>
						<th>Kund</th><th>Faktura.nr</th><th>Betaldatum</th>
					</tr>
				</thead>
				<tbody>
					<?php foreach ($this->overdueInvoices as $invoice) { ?>

						<tr class="clickable" data-link="/invoice/view/<?= $invoice['invoice_id'] ?>">
							<td><a href="/customer/view/<?= $invoice['customer'] ?>"><?= $invoice['name'] ?></a></td>
							<td><?= $invoice['invoice_number'] ?></td>
							<td><?= date('Y-m-d', $invoice['due']) ?></td>
						</tr>

					<?php } ?>
				</tbody>
			</table>
		</div>
	</div>

</div>