<section id="content">
<?php


    $form = new Emilk_Form();
    $form->setAttr('class', 123)
         ->setAttr('method', 'post');

    $element1 = new Emilk_Form_Element_Text('namn1');
    $element1->setValue('värde')
             ->setAttr('id', 'idet')
             ->setAttr('class', 'class1 class2')
             ->setValidation('integer', 'måste vara ett heltal');

    $element2 = new Emilk_Form_Element_Text('namn2');

    $form->add(array($element1, $element2));






    print_r($form);

    echo '<br><br>';

    $form->render();

    $form->validate();


?>
</section>