<div class="g12 nodrop">
	<h1>Dashboard</h1>
</div>

<div class="g6 widgets">

	<div class="widget" id="widget_order_date" data-icon="create_write">
		<h3 class="handle">Order dates</h3>
		<div>
			<table class="datatable">
				<thead>
					<tr>
						<th>Date</th>
						<th>Orders</th>
						<th>Items</th>
					</tr>
				</thead>
				<tbody>

					<?php foreach($this->orderDates as $date) { ?>

					<tr>
						<td><?= ($date['delivery_date'] ? date('Y-m-d', $date['delivery_date']): ''); ?></td>
						<td><?= $date['orders']; ?></td>
						<td><?= $date['items']; ?></td>
					</tr>

					<?php } ?>

				</tbody>
			</table>
		</div>
	</div>

	<!-- <div class="widget" id="calendar_widget" data-icon="calendar">
		<h3 class="handle">Calendar</h3>
		<div>
			<div class="calendar" data-header="small">
			</div>
			<p>
			<a class="btn" href="calendar.html">Check out the Calendar section</a>
			</p>
		</div>
	</div> -->

	<!-- <div class="widget number-widget" id="widget_CRM" data-icon="folder_love">
		<h3 class="handle">CRM</h3>
		<div>
			<ul>
				<li><a href=""><span>7423</span> New tickets</a></li>
				<li><a href=""><span>392</span> Critical tickets</a></li>
				<li><a href=""><span>153</span> Active ticets</a></li>
			</ul>
		</div>
	</div> -->

	<!-- <div class="widget number-widget" id="widget_monitoring" data-icon="graph">
		<h3 class="handle">Monitoring</h3>
		<div>
			<ul>
				<li><a href=""><span>870</span> Orders processed this month</a></li>
				<li><a href=""><span>413</span> Deliveries done this month</a></li>
				<li><a href=""><span>153</span> Invoices sent this month</a></li>
			</ul>
		</div>
	</div>
 -->
	<!-- <div class="widget" id="overdue-invoice" data-icon="cash_register">
		<h3 class="handle">Overdue invoices</h3>
		<div>

			<table class="datatable">
				<thead>
					<tr>
						<th>Customer</th><th>Invoice nr.</th><th>Overdue date</th>
					</tr>
				</thead>
				<tbody>
					<tr class="">
						<td>Customer LT.</td><td>109</td><td>2012-10-14</td>
					</tr>
					<tr class="">
						<td>Customer LT.</td><td>119</td><td>2012-07-22</td>
					</tr>
					<tr class="">
						<td>Customer LT.</td><td>169</td><td>2012-08-28</td>
					</tr>
					<tr class="">
						<td>Customer LT.</td><td>94</td><td>2012-09-16</td>
					</tr>
					<tr class="">
						<td>Customer LT.</td><td>111</td><td>2012-10-17</td>
					</tr>
				</tbody>
			</table>

		</div>

	</div> -->

</div>


<div class="g6 widgets">
		
	
	<!-- <div class="widget" id="widget_unconfirmedorders" data-icon="create_write">
		<h3 class="handle">Unconfirmed orders</h3>
		<div>
			x
		</div>
	</div> -->

	

</div>