<div class="g12">
<h1>Invoice #0000</h1>
<p>A new invoice requires a existing customer in the system.</p>
	<form id="form" method="post" autocomplete="off">
		<fieldset>
		<label>Customer</label>
			<section><label for="customerid">Customer<br><span>Enter customer name or ID</span></label>
				<div><input id="customerid" name="customerid" type="text" class="autocomplete" required data-errortext="You can't add a new order without a customer">
				</div>
			</section>
		</fieldset>
		<fieldset>
		<label>Invoice date</label>
			<section><label for="invoice_date">Invoice date</label>
				<div><input id="invoice_date" name="invoice_date" type="text" class="date" data-value="now">
				</div>
			</section>
			<section><label for="invoice_due">Invoice due</label>
				<div><input id="invoice_due" name="invoice_due" type="text" class="date" data-value="+30">
				</div>
			</section>
		</fieldset>
		<fieldset>
			<label>Products</label>
			<section><label for="invoice_content">Add products to invoice</label>
				<div>
					<input id="product" name="product" type="text" class="g5" placeholder="Product"></input>
					<input id="qty" name="qty" type="number" class="decimal g4" placeholder="Quantity">
					<input id="unit_price" name="unit_price" type="number" class="decimal g4" placeholder="Unit price">
					<span class="g3 pull-right align-right"><strong>2500kr</strong></span>
				</div>
			</section>
			<section>
				<div>
					<input id="product" name="product" type="text" class="g5" placeholder="Product"></input>
					<input id="qty" name="qty" type="number" class="decimal g4" placeholder="Quantity">
					<input id="unit_price" name="unit_price" type="number" class="decimal g4" placeholder="Unit price">
					<span class="g3 pull-right align-right"><strong>2500kr</strong></span>
				</div>
			</section>
			<section><label for="invoice_content"><strong>Subtotal</strong></label>
				<div>
					<span class="g3 pull-right align-right"><strong>2500kr</strong></span>
				</div>
			</section>
			<section><label for="invoice_content"><strong>Tax 25%</strong></label>
				<div>
					<span class="g3 pull-right align-right"><strong>2500kr</strong></span>
				</div>
			</section>
			<section class="total_due"><label for="total_due"><strong>Total Due</strong></label>
				<div>
					<span class="g3 pull-right align-right"><strong>2500kr</strong></span>
				</div>
			</section>
		</fieldset>
		<fieldset>
			<label>Notes</label>
			<section><label for="invoice_notes">Notes to print on the invoice</label>
				<div><textarea id="invoice_notes" name="invoice_notes" data-autogrow="true"></textarea>
				</div>
			</section>
		</fieldset>
		<fieldset>
			<label>Create new invoice</label>
			<section>
				<div><button class="submit green" name="Create invoice" value="submit">Create invoice</button></div>
			</section>
		</fieldset>
	</form>	

</div>	