<div class="g12">
   <h1>Invoices</h1>
   <p></p>
   <table class="datatable">
      <thead>
         <tr>
            <th>Invoice number</th>
            <th>Customer</th>
            <th>Invoice date</th>
            <th>Due date</th>
            <th>Status</th>
         </tr>
      </thead>
      <tbody>
         <tr class="gradeX">
            <td><a href="#">102</a></td>
            <td>Pelles bygg</td>
            <td>2012-01-04</td>
            <td>2012-02-03</td>
            <td>UNPAID</td>
         </tr>
         <tr class="gradeA">
            <td><a href="#">101</a></td>
            <td>Gunde Svan</td>
            <td>2012-01-01</td>
            <td>2012-01-31</td>
            <td>PAID</td>
         </tr>
      </tbody>
   </table>
</div>
