<?php if($this->isAdmin) { ?>
   <a href="/invoice/add"><button>Add invoice</button></a>
<?php } ?>

<div class="g12">
   <h1>Invoices</h1>
   <table class="datatable">
      <thead>
         <tr>
            <th>Invoice number</th>
            <th>Customer</th>
            <th>Invoice date</th>
            <th>Due date</th>
            <th>Status</th>
         </tr>
      </thead>
      <tbody>

         <?php foreach($this->invoices as $invoice) { ?>

            <tr class="clickable" data-link="/invoice/view/<?= $invoice['invoice_id'] ?>">
               <td><?= $invoice['invoice_number'] ?></td>
               <td><a href="/customer/view/<?= $invoice['customer_id'] ?>"><?= $invoice['name'] ?></td>
               <td><?= date('Y-m-d', $invoice['date']) /*ADD + 1 HOUR*/?></td>
               <td><?= date('Y-m-d', $invoice['due']) ?></td>
               <td><?= $invoice['status'] ?></td>
            </tr>

         <?php } ?>

      </tbody>
   </table>
</div>