<?php if($this->isAdmin) { ?>
	<a href="/product/add"><button>Add product</button></a>
<?php } ?>

<div class="g12">
	<h1>Products</h1>
	<table class="datatable">
		<thead>
			<tr>
				<th>Product number</th>
				<th>Product</th>
				<th>Price</th>
				<th>Unit</th>
				<th>Status</th>

			</tr>
		</thead>
		<tbody>

			<?php foreach($this->products as $product) { ?>

				<tr class="gradeX">
					<td><a href="/product/view/<?= $product['product_id'] ?>"><?= $product['product_number'] ?></a></td>
					<td><?= $product['product'] ?></td>
					<td><?= $product['price'] ?></td>
					<td><?= $product['unit'] ?></td>
					<td><?= $product['status'] ?></td>
				</tr>

			<?php } ?>

		</tbody>
	</table>
</div>