<?php if($this->isAdmin) { ?>
	<a href="/product/add"><button>Add product</button></a>
<?php } ?>

<div class="g12">
	<h1>Products</h1>
	<table class="datatable">
		<thead>
			<tr>
				<th>Product number</th>
				<th>Product</th>
				<th>Price</th>
				<th>Unit</th>
				<th>Status</th>

			</tr>
		</thead>
		<tbody>

			<?php 
				foreach($this->products as $product) {

				$color = '';
				if($product['status'] == 'available') {
					$color = 'green';
				} elseif ($product['status'] == 'out of stock') {
					$color = 'red';
				}
			?>

				<tr class="clickable <?= $color ?>" data-link="/product/view/<?= $product['product_id'] ?>">
					<td><?= $product['product_number'] ?></td>
					<td><?= $product['product'] ?></td>
					<td><?= $product['price'] ?></td>
					<td><?= $product['unit'] ?></td>
					<td><?= $product['status'] ?></td>
				</tr>

			<?php } ?>

		</tbody>
	</table>
</div>