<?php if($this->isAdmin) { ?>
	<a href="/order/add"><button>Add order</button></a>
<?php } ?>

<div class="g12">
	<h1><?= (isset($this->completed)? 'Completed ': 'Active '); ?>orders</h1>
	<table class="datatable">
		<thead>
			<tr>
				<th>Order number</th>
				<th>Customer</th>
				<th>Delivery</th>
				<th>Delivary date</th>
				<th>Notes</th>
				<th>Items</th>

				<?php
					if(!$this->showAll){
						if($this->customs[0]['custom_field_1']) {
				?>
					<th><?= $this->customs[0]['custom_field_1'] ?></th>
				<?php
						}
						if($this->customs[0]['custom_field_2']) {
				?>
					<th><?= $this->customs[0]['custom_field_2'] ?></th>
				<?php
						}
						if($this->customs[0]['custom_field_3']) {
				?>
					<th><?= $this->customs[0]['custom_field_3'] ?></th>
				<?php
						}
					}
				?>

				<th>Status</th>

			</tr>
		</thead>
		<tbody>

			<?php 
				foreach($this->orders as $order) {

				$color = '';
				if($order['status'] == 'new') {
					$color = 'blue';
				} elseif ($order['status'] == 'active') {
					$color = 'yellow';
				} elseif ($order['status'] == 'completed') {
					$color = 'green';
				} elseif ($order['status'] == 'invoice') {
					$color = 'orange';
				}

			?>

				<tr class="clickable <?= $color ?>" data-link="/order/view/<?= $order['order_id'] ?>">
					<td><?= $order['order_number'] ?></td>
					<td>
						<a href="/customer/view/<?= $order['customer_id'] ?>"><?= $order['name'] ?></a>
					</td>
					<td>
						<a href="#" class="changeDeliveryStatus noColor" data-id="<?= $order['order_id'] ?>"><?= $order['delivery'] ?></a>
					</td>
					<td><?= ($order['delivery_date'] ? date('Y-m-d', $order['delivery_date']): '') ?></td>
					<td><?= ($order['notes'] ? 'yes' : '') ?></td>
					<td><?= $order['quantity'] ?></td>

					<?php
						if(!$this->showAll){
							if($this->customs[0]['custom_field_1']) {
					?>
						<td><?= $order['custom_1'] ?></td>
					<?php
							}
							if($this->customs[0]['custom_field_2']) {
					?>
						<td><?= $order['custom_2'] ?></td>
					<?php
							}
							if($this->customs[0]['custom_field_3']) {
					?>
						<td><?= $order['custom_3'] ?></td>
					<?php
							}
						}
					?>

					<td>
						<a href="#" class="changeOrderStatus" data-id="<?= $order['order_id'] ?>"><?= $order['status'] ?></a>
					</td>

				</tr>

			<?php } ?>

		</tbody>
	</table>
</div>	