<?php if($this->isAdmin) { ?>
	<a href="/order/add"><button>Add order</button></a>
<?php } ?>

<div class="g12">
	<h1>Orders</h1>
	<table class="datatable">
		<thead>
			<tr>
				<th>Order number</th>
				<th>Customer</th>
				<th>Status</th>
				<th>Delivery</th>
				<th>Delivary date</th>
				<th>Notes</th>
				<th>Items</th>

				<?php
					if(!$this->showAll){
						if($this->customs[0]['custom_field_1']) {
				?>
					<th><?= $this->customs[0]['custom_field_1'] ?></th>
				<?php
						}
						if($this->customs[0]['custom_field_2']) {
				?>
					<th><?= $this->customs[0]['custom_field_2'] ?></th>
				<?php
						}
						if($this->customs[0]['custom_field_3']) {
				?>
					<th><?= $this->customs[0]['custom_field_3'] ?></th>
				<?php
						}
					}
				?>

			</tr>
		</thead>
		<tbody>

			<?php foreach($this->orders as $order) { ?>

				<tr class="clickable" data-link="/order/view/<?= $order['order_id'] ?>">
					<td><?= $order['order_number'] ?></td>
					<td><a href="/customer/view/<?= $order['customer_id'] ?>"><?= $order['name'] ?></a></td>
					<td><?= $order['status'] ?></td>
					<td><?= $order['delivery'] ?></td>
					<td><?= ($order['delivery_date'] ? date('Y-m-d', $order['delivery_date']): '') ?></td>
					<td><?= ($order['notes'] ? 'yes' : '') ?></td>
					<td><?= $order['quantity'] ?></td>

					<?php
						if(!$this->showAll){
							if($this->customs[0]['custom_field_1']) {
					?>
						<td><?= $order['custom_1'] ?></td>
					<?php
							}
							if($this->customs[0]['custom_field_2']) {
					?>
						<td><?= $order['custom_2'] ?></td>
					<?php
							}
							if($this->customs[0]['custom_field_3']) {
					?>
						<td><?= $order['custom_3'] ?></td>
					<?php
							}
						}
					?>

				</tr>

			<?php } ?>

		</tbody>
	</table>


	<h1>Ordered products</h1>
	<table class="datatable">
		<thead>
			<tr>
				<th>Product</th>
				<th>Quantity</th>
			</tr>
		</thead>
		<tbody>

			<?php foreach($this->orderedProducts as $product) { ?>

				<tr>
					<td><a href="/product/view/<?= $product['product_id'] ?>"><?= $product['product'] ?></a></td>
					<td><?= $product['quantity'] ?></td>
				</tr>

			<?php } ?>

		</tbody>
	</table>





</div>	