<?php if($this->isAdmin) { ?>
	<a href="/order/add"><button>Add order</button></a>
<?php } ?>

<div class="g12">
	<h1>Orders</h1>
	<table class="datatable">
		<thead>
			<tr>
				<th>Order number</th>
				<th>Order date</th>
				<th>Customer</th>
				<th>Status</th>
				<th>Delivery</th>

				<?php
					if(!$this->showAll){
						if($this->customs[0]['custom_field_1']) {
				?>
					<th><?= $this->customs[0]['custom_field_1'] ?></th>
				<?php
						}
						if($this->customs[0]['custom_field_2']) {
				?>
					<th><?= $this->customs[0]['custom_field_2'] ?></th>
				<?php
						}
						if($this->customs[0]['custom_field_3']) {
				?>
					<th><?= $this->customs[0]['custom_field_3'] ?></th>
				<?php
						}
					}
				?>

			</tr>
		</thead>
		<tbody>

			<?php foreach($this->orders as $order) { ?>

				<tr class="gradeX">
					<td><a href="/order/<?= $order['order_id'] ?>"><?= $order['order_number'] ?></a></td>
					<td><?= date('Y-m-d', $order['delivery_date']) ?></td>
					<td><a href="/customer/<?= $order['customer_id'] ?>"><?= $order['name'] ?></a></td>
					<td><?= $order['status'] ?></td>
					<td><?= $order['delivery'] ?></td>

					<?php
						if(!$this->showAll){
							if($this->customs[0]['custom_field_1']) {
					?>
						<td><?= $order['custom_1'] ?></td>
					<?php
							}
							if($this->customs[0]['custom_field_2']) {
					?>
						<td><?= $order['custom_2'] ?></td>
					<?php
							}
							if($this->customs[0]['custom_field_3']) {
					?>
						<td><?= $order['custom_3'] ?></td>
					<?php
							}
						}
					?>

				</tr>

			<?php } ?>

		</tbody>
	</table>
</div>	