<div class="g12">
   <h1>My deliveries <?php echo ($this->date? $this->date: 'Today') ?> (<?= count($this->deliveries) ?>)</h1>
   <table id="deliveries" class="datatable">
      <thead>
         <tr>
         	<th style="width:40px">Order Number</th>
            <th>Customer</th>
            <th>Items</th>
            <th>Time</th>
            <th>Delivery adress</th>
            <th>Notes</th>
            <th>Order status</th>
            <th>Delivery status</th>
         </tr>
      </thead>
      <tbody>

         <?php
            foreach($this->deliveries as $delivery) {

            $color = '';
            if($delivery['delivery'] == 'approved') {
               $color = 'yellow';
            } else  {
               $color = 'blue';
            }
         ?>

            <tr class="clickable <?= $color ?>" data-link="/order/view/<?= $delivery['order_id'] ?>">
               <td><?= $delivery['order_number'] ?></td>
               <td><a href="/customer/view/<?= $delivery['customer_id'] ?>"><?= $delivery['name'] ?></a></td>
               <td><?= $delivery['items'] ?></td>
               <td><?= date('H:i', $delivery['delivery_date']) ?></td>
               <td>
					   <a target="_blank" href="http://maps.google.com/?q=<?= $delivery['delivery_adress'] ?>">
                    	<?= $delivery['delivery_adress'] ?>
                  </a>
               </td>
               <td><?= ($delivery['notes'] ? 'yes' : '') ?></td>
               <td><a href="#" class="changeOrderStatus noColor" data-id="<?= $delivery['order_id'] ?>"><?= $delivery['status'] ?></a></td>
               <td><a href="#" class="changeDeliveryStatus" data-id="<?= $delivery['order_id'] ?>"><?= $delivery['delivery'] ?></a></td>
            </tr>

         <?php } ?>

      </tbody>
   </table>
</div>

<div class="g4 fr" style="text-align:right">
   <h1>Select specific date</h1>
   <input type="text" id="changeDeliveryDate" class="date mine" value="<?php echo ($this->date? $this->date: '') ?>">
</div>