<div class="g12">
   <h1><?php echo ($this->date? $this->date: 'Dagens') ?> leveranser (<?= count($this->deliveries) ?>)</h1>
   <table id="deliveries" class="datatable">
      <thead>
         <tr>
            <th style="width:23px"></th>
            <th>Bud</th>
         	<th>Ordernr</th>
            <th>Kund</th>
            <th>Produkter</th>
            <th>Tid</th>
            <th>Leveransadress</th>
            <th>Anteckningar</th>
            <th>Status</th>
         </tr>
      </thead>
      <tbody>

         <?php
            foreach($this->deliveries as $delivery) {

            $color = '';
            if(isset($delivery['carrier'])) {
               $color = 'blue';
            } else  {
               $color = 'red';
            }
         ?>

            <tr class="clickable <?= $color ?>" data-link="function(checkDelivery)" data-order-id="<?= $delivery['order_id'] ?>">
               <td><input disabled type="checkbox" value="<?= $delivery['carrierId']?>"></td><!-- OBS!!! måste vara disabled -->
               <td class="carrier"><?= (isset($delivery['carrier']) ? ucfirst($delivery['carrier']) : '') ?></td>
               <td><a href="/order/view/<?= $delivery['order_id'] ?>"><?= $delivery['order_number'] ?></a></td>
               <td><a href="/customer/view/<?= $delivery['customer_id'] ?>"><?= $delivery['name'] ?></a></td>
               <td><?= $delivery['items'] ?></td>
               <td><?= date('H:i', $delivery['delivery_date']) ?></td>
               <td>
					   <a target="_blank" href="http://maps.google.com/?q=<?= $delivery['delivery_adress'] ?>">
                    	<?= $delivery['delivery_adress'] ?>
                  </a>
               </td>
               <td><?= ($delivery['notes'] ? 'yes' : '') ?></td>
               <td><?= $delivery['status'] ?></td>
            </tr>

         <?php } ?>

      </tbody>
   </table>

   <span id="selectAll">Markera/avmarkera alla</span>
</div>


<div class="g12">
   <h1>Välj bud <span id="numSelected"></span></h1>
   <select id="carriers">
      <option value="0">Välj vem som kör budet</option>

      <?php foreach($this->users as $user) { ?>

         <option value="<?= $user['id'] ?>"><?= ucfirst($user['name']) ?></option>

      <?php } ?>

   </select>
   <!-- <button id="removeCarrier" class="red">Ta bort</button> -->
</div>

<div class="g4 fr" style="text-align:right">
   <h1>Granska uykörningar den:</h1>
   <input type="text" id="changeDeliveryDate" class="date view" value="<?php echo ($this->date? $this->date: '') ?>">
</div>