<div class="g12">
   <h1>Today's deliveries</h1>
   <table class="datatable">
      <thead>
         <tr>
         	<th>Order Number</th>
            <th>Customer</th>
            <th>Items</th>
            <th>Time</th>
            <th>Delivery adress</th>
            <th>Notes</th>
            <th>Status</th>
         </tr>
      </thead>
      <tbody>

         <?php foreach($this->deliveries as $delivery) {
         	// if(!$delivery['order_id']) {
         	// 	break;
         	// }
         ?>

            <tr class="clickable" data-link="/order/view/<?= $delivery['order_id'] ?>">
               <td><?= $delivery['order_number'] ?></td>
               <td><a href="/customer/view/<?= $delivery['customer_id'] ?>"><?= $delivery['name'] ?></a></td>
               <td><?= $delivery['items'] ?></td>
               <td><?= date('H:i', $delivery['delivery_date']) ?></td>
               <td>
					<a target="_blank" href="http://maps.google.com/?q=<?= $delivery['delivery_adress'] ?>">
                    	<?= $delivery['delivery_adress'] ?>
                  	</a>
               </td>
               <td><?= ($delivery['notes'] ? 'yes' : '') ?></td>
               <td><a href="#" class="changeStatus" data-id="<?= $delivery['order_id'] ?>"><?= $delivery['status'] ?></a></td>
            </tr>

         <?php } ?>

      </tbody>
   </table>
</div>