<?php if($this->isAdmin) { ?>
   <a href="/cr/add"><button>Lägg till uppgift</button></a>
<?php } ?>

<div class="g12">
   <h1><?= (isset($this->completed)? 'Completed ': 'Active ') ?>Uppgifter</h1>
   <table class="datatable">
      <thead>
         <tr>
            <th>Kund</th>
            <th>Datum</th>
            <th>Status</th>
         </tr>
      </thead>
      <tbody>

         <?php 
            foreach($this->crs as $cr) {

            $color = '';
            if($cr['status'] == 'active') {
               $color = 'yellow';
            } elseif ($cr['status'] == 'completed') {
               $color = 'green';
            }

         ?>

            <tr class="clickable <?= $color ?>" data-link="/cr/view/<?= $cr['crs_id'] ?>">
               <td><a href="/customer/view/<?= $cr['customer_id'] ?>"><?= $cr['name'] ?></td>
               <td><?= date('Y-m-d', $cr['date']) /*ADD + 1 HOUR*/?></td>
               <td><a href="#" class="changeCrStatus" data-id="<?= $cr['crs_id'] ?>"><?= $cr['status'] ?></a></td>
            </tr>

         <?php } ?>

      </tbody>
   </table>
</div>