<?php
	$controllerName = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
	$actionName = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
?>

<!doctype html>
<html lang="en-us">
	<head>

		<?php include APPLICATION_PATH . '/views/layout/head.php'; ?>

	</head>
	<body id="<?= $controllerName ?>" class="<?= $actionName ?>">

		<?php
			if(isset($this->user->mail) && isset($_SESSION['business'])) {
				// businesses
				$db = Zend_Registry::get('db');

				$select = $db->select()
							 ->from('businesses', 'business')
							 ->joinLeft('user_access', 'businesses.business_id = user_access.business', 'business as business_id')
							 ->where('user_access.user = ' . $this->user->id)
							 ->order('business ASC');
				$businesses = $db->fetchAll($select);

				// num things
				$numOrders = $db->fetchAll('SELECT COUNT(order_id) as "0" FROM orders WHERE business = ' . $_SESSION['business']);
				$numProducts = $db->fetchAll('SELECT COUNT(product_id) as "0" FROM products WHERE status <> "deleted" AND business = ' . $_SESSION['business']);
				$numCustomers = $db->fetchAll('SELECT COUNT(customer_id) as "0" FROM customers WHERE business = ' . $_SESSION['business']);
				$numInvoices = $db->fetchAll('SELECT COUNT(invoice_id) as "0" FROM invoices WHERE business = ' . $_SESSION['business']);

				include APPLICATION_PATH . '/views/layout/top.html';
				include APPLICATION_PATH . '/views/layout/nav.php';
			}
		?>

		<section id="content">

			<?= $this->layout()->content; ?>

		</section>

		<?php include APPLICATION_PATH . '/views/layout/foot.html'; ?>

	</body>
</html>

