<?php
	$controllerName = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
	$actionName = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
?>

<!doctype html>
<html lang="en-us">
	<head>

		<?php include APPLICATION_PATH . '/views/layout/head.php'; ?>

	</head>
	<body id="<?= $controllerName ?>" class="<?= $actionName ?>">

		<?php
			if(isset($this->user->mail) && isset($_SESSION['business'])) {

				// is admin
				$role = $this->user->role;
		        $acl = new Model_LibraryAcl;
		        $adminVal =  array_search('admin', $acl::$roles);
		        $roleVal =  array_search($role, $acl::$roles);

		        $isAdmin = false;
		        if($roleVal >= $adminVal) {
		            $isAdmin = true;
		        }

				// businesses
				$db = Zend_Registry::get('db');

				$today = strtotime(date('Y-m-d'));
				$tomorrow = $today + 24*60*60;

				$select = $db->select()
							 ->from('businesses', 'business')
							 ->joinLeft('user_access', 'businesses.business_id = user_access.business', 'business as business_id')
							 ->where('user_access.user = ' . $this->user->id)
							 ->order('business ASC');
				$businesses = $db->fetchAll($select);

				// num things
				$numOrders = $db->fetchAll('SELECT COUNT(order_id) as "quantity" FROM orders WHERE business = ' . $_SESSION['business'] . ' AND (orders.status = "new" OR orders.status = "active")');
				$numProducts = $db->fetchAll('SELECT COUNT(product_id) as "quantity" FROM products WHERE status <> "deleted" AND business = ' . $_SESSION['business']);
				$numCustomers = $db->fetchAll('SELECT COUNT(customer_id) as "quantity" FROM customers WHERE business = ' . $_SESSION['business']);
				$numInvoices = $db->fetchAll('SELECT COUNT(invoice_id) as "quantity" FROM invoices WHERE business = ' . $_SESSION['business'] . ' AND status = "unpaid"');
				$numCrs = $db->fetchAll('SELECT COUNT(crs_id) as "quantity" FROM crs WHERE business = ' . $_SESSION['business'] . ' AND status = "active" AND date < ' . $tomorrow);

				$select = $db->select()
	                		 ->from('orders', 'COUNT(order_id) as quantity')
	                		 ->where('orders.business = ' . $_SESSION['business'])
	                		 ->where('orders.delivery_date >= "' . $today . '"')
	                		 ->where('orders.delivery_date < "' . $tomorrow . '"')
	                		 ->where('orders.delivery <> ?', 'completed')
	                		 ->where('orders.carrier = ?', $this->user->id);
	    		$numMyDeliveries = $db->fetchAll($select);

	    		$select = $db->select()
	                		 ->from('orders', 'COUNT(order_id) as quantity')
	                		 ->where('orders.business = ' . $_SESSION['business'])
	                		 ->where('orders.delivery_date >= "' . $today . '"')
	                		 ->where('orders.delivery_date < "' . $tomorrow . '"')
	                		 ->where('orders.status <> "new"')
	                		 ->where('orders.delivery = ?', 'approved')
	                		 ->where('orders.carrier = ?', 0);
	    		$numFreeDeliveries = $db->fetchAll($select);


				include APPLICATION_PATH . '/views/layout/top.html';
				include APPLICATION_PATH . '/views/layout/nav.php';
			}
		?>

		<section id="content">

			<?= $this->layout()->content; ?>

		</section>

		<?php include APPLICATION_PATH . '/views/layout/foot.html'; ?>

	</body>
</html>

